name: "${project.artifactId}"
version: "${project.version}"
api-version: "1.13"
main: nl.martenm.servertutorialplus.ServerTutorialPlus
author: MartenM
authors:
  - Rakdos8
description: "ยง6The plugin to guide players around your server using tutorials."
softdepend: [PlaceholderAPI, Multiverse-Core, MultiWorld]
commands:
  servertutorial:
    description: "All the servertutorial plus commands"
    aliases: [st]
